# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkgs/platform/content.proto

require 'google/protobuf'


descriptor_data = "\n\x1bpkgs/platform/content.proto\"\"\n\x04\x46ile\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04Name\x18\x02 \x01(\t\"w\n\x0e\x44iscordContent\x12\x0f\n\x07\x43ommand\x18\x01 \x01(\t\x12\'\n\x04\x41rgs\x18\x02 \x03(\x0b\x32\x19.DiscordContent.ArgsEntry\x1a+\n\tArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"C\n\x0b\x44iscordResp\x12\x0f\n\x07Message\x18\x01 \x01(\t\x12\r\n\x05\x45mbed\x18\x02 \x01(\t\x12\x14\n\x05\x46iles\x18\x03 \x03(\x0b\x32\x05.FileB\x0cZ\n./functionb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

File = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("File").msgclass
DiscordContent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DiscordContent").msgclass
DiscordResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DiscordResp").msgclass
