// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Funcmeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Funcmeta) Reset() {
	*x = Funcmeta{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Funcmeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Funcmeta) ProtoMessage() {}

func (x *Funcmeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Funcmeta.ProtoReflect.Descriptor instead.
func (*Funcmeta) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *Funcmeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Funcmeta) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DiscordContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=Command,proto3" json:"Command,omitempty"`
	Args          map[string]string      `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Funcmeta      *Funcmeta              `protobuf:"bytes,3,opt,name=Funcmeta,proto3" json:"Funcmeta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordContent) Reset() {
	*x = DiscordContent{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordContent) ProtoMessage() {}

func (x *DiscordContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordContent.ProtoReflect.Descriptor instead.
func (*DiscordContent) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *DiscordContent) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DiscordContent) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *DiscordContent) GetFuncmeta() *Funcmeta {
	if x != nil {
		return x.Funcmeta
	}
	return nil
}

type DiscordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Embed         string                 `protobuf:"bytes,2,opt,name=Embed,proto3" json:"Embed,omitempty"`
	Files         []*File                `protobuf:"bytes,3,rep,name=Files,proto3" json:"Files,omitempty"`
	Funcmeta      *Funcmeta              `protobuf:"bytes,4,opt,name=Funcmeta,proto3" json:"Funcmeta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordResp) Reset() {
	*x = DiscordResp{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordResp) ProtoMessage() {}

func (x *DiscordResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordResp.ProtoReflect.Descriptor instead.
func (*DiscordResp) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *DiscordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DiscordResp) GetEmbed() string {
	if x != nil {
		return x.Embed
	}
	return ""
}

func (x *DiscordResp) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DiscordResp) GetFuncmeta() *Funcmeta {
	if x != nil {
		return x.Funcmeta
	}
	return nil
}

type FuncInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       string                 `protobuf:"bytes,1,opt,name=GuildId,proto3" json:"GuildId,omitempty"`
	Secrets       map[string]string      `protobuf:"bytes,2,rep,name=Secrets,proto3" json:"Secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuncInit) Reset() {
	*x = FuncInit{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuncInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuncInit) ProtoMessage() {}

func (x *FuncInit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuncInit.ProtoReflect.Descriptor instead.
func (*FuncInit) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *FuncInit) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *FuncInit) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\"0\n" +
	"\bFuncmeta\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x14\n" +
	"\x05MsgId\x18\x02 \x01(\tR\x05MsgId\".\n" +
	"\x04File\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"\xb9\x01\n" +
	"\x0eDiscordContent\x12\x18\n" +
	"\aCommand\x18\x01 \x01(\tR\aCommand\x12-\n" +
	"\x04Args\x18\x02 \x03(\v2\x19.DiscordContent.ArgsEntryR\x04Args\x12%\n" +
	"\bFuncmeta\x18\x03 \x01(\v2\t.FuncmetaR\bFuncmeta\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\vDiscordResp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x14\n" +
	"\x05Embed\x18\x02 \x01(\tR\x05Embed\x12\x1b\n" +
	"\x05Files\x18\x03 \x03(\v2\x05.FileR\x05Files\x12%\n" +
	"\bFuncmeta\x18\x04 \x01(\v2\t.FuncmetaR\bFuncmeta\"\x92\x01\n" +
	"\bFuncInit\x12\x18\n" +
	"\aGuildId\x18\x01 \x01(\tR\aGuildId\x120\n" +
	"\aSecrets\x18\x02 \x03(\v2\x16.FuncInit.SecretsEntryR\aSecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012p\n" +
	"\vDiscordFaaS\x125\n" +
	"\x14HandleDiscordCommand\x12\x0f.DiscordContent\x1a\f.DiscordResp\x12*\n" +
	"\x12InitializeFunction\x12\t.FuncInit\x1a\t.FuncmetaB+Z)github.com/f4tal-err0r/discord_faas/protob\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_service_proto_goTypes = []any{
	(*Funcmeta)(nil),       // 0: Funcmeta
	(*File)(nil),           // 1: File
	(*DiscordContent)(nil), // 2: DiscordContent
	(*DiscordResp)(nil),    // 3: DiscordResp
	(*FuncInit)(nil),       // 4: FuncInit
	nil,                    // 5: DiscordContent.ArgsEntry
	nil,                    // 6: FuncInit.SecretsEntry
}
var file_proto_service_proto_depIdxs = []int32{
	5, // 0: DiscordContent.Args:type_name -> DiscordContent.ArgsEntry
	0, // 1: DiscordContent.Funcmeta:type_name -> Funcmeta
	1, // 2: DiscordResp.Files:type_name -> File
	0, // 3: DiscordResp.Funcmeta:type_name -> Funcmeta
	6, // 4: FuncInit.Secrets:type_name -> FuncInit.SecretsEntry
	2, // 5: DiscordFaaS.HandleDiscordCommand:input_type -> DiscordContent
	4, // 6: DiscordFaaS.InitializeFunction:input_type -> FuncInit
	3, // 7: DiscordFaaS.HandleDiscordCommand:output_type -> DiscordResp
	0, // 8: DiscordFaaS.InitializeFunction:output_type -> Funcmeta
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
