// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/v1/models.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	GuildId       string                 `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContext) Reset() {
	*x = GetContext{}
	mi := &file_api_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContext) ProtoMessage() {}

func (x *GetContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContext.ProtoReflect.Descriptor instead.
func (*GetContext) Descriptor() ([]byte, []int) {
	return file_api_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *GetContext) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetContext) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

type Args struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_api_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_api_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *Args) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Args) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Args) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type Commands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Args          []*Args                `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commands) Reset() {
	*x = Commands{}
	mi := &file_api_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commands) ProtoMessage() {}

func (x *Commands) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commands.ProtoReflect.Descriptor instead.
func (*Commands) Descriptor() ([]byte, []int) {
	return file_api_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *Commands) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Commands) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Commands) GetArgs() []*Args {
	if x != nil {
		return x.Args
	}
	return nil
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_api_v1_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_api_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BuildFunc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Runtime       string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	GuildId       string                 `protobuf:"bytes,3,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Commands      []*Commands            `protobuf:"bytes,6,rep,name=commands,proto3" json:"commands,omitempty"`
	Envvars       []*EnvVar              `protobuf:"bytes,7,rep,name=envvars,proto3" json:"envvars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFunc) Reset() {
	*x = BuildFunc{}
	mi := &file_api_v1_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFunc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFunc) ProtoMessage() {}

func (x *BuildFunc) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFunc.ProtoReflect.Descriptor instead.
func (*BuildFunc) Descriptor() ([]byte, []int) {
	return file_api_v1_models_proto_rawDescGZIP(), []int{4}
}

func (x *BuildFunc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildFunc) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *BuildFunc) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *BuildFunc) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BuildFunc) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BuildFunc) GetCommands() []*Commands {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *BuildFunc) GetEnvvars() []*EnvVar {
	if x != nil {
		return x.Envvars
	}
	return nil
}

type ContextResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GuildId        string                 `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	GuildName      string                 `protobuf:"bytes,3,opt,name=guild_name,json=guildName,proto3" json:"guild_name,omitempty"`
	ServerUrl      string                 `protobuf:"bytes,4,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	CurrentContext bool                   `protobuf:"varint,5,opt,name=current_context,json=currentContext,proto3" json:"current_context,omitempty"`
	JwToken        string                 `protobuf:"bytes,6,opt,name=jw_token,json=jwToken,proto3" json:"jw_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContextResp) Reset() {
	*x = ContextResp{}
	mi := &file_api_v1_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResp) ProtoMessage() {}

func (x *ContextResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResp.ProtoReflect.Descriptor instead.
func (*ContextResp) Descriptor() ([]byte, []int) {
	return file_api_v1_models_proto_rawDescGZIP(), []int{5}
}

func (x *ContextResp) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ContextResp) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *ContextResp) GetGuildName() string {
	if x != nil {
		return x.GuildName
	}
	return ""
}

func (x *ContextResp) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *ContextResp) GetCurrentContext() bool {
	if x != nil {
		return x.CurrentContext
	}
	return false
}

func (x *ContextResp) GetJwToken() string {
	if x != nil {
		return x.JwToken
	}
	return ""
}

type ListFunctions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*Function            `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctions) Reset() {
	*x = ListFunctions{}
	mi := &file_api_v1_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctions) ProtoMessage() {}

func (x *ListFunctions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctions.ProtoReflect.Descriptor instead.
func (*ListFunctions) Descriptor() ([]byte, []int) {
	return file_api_v1_models_proto_rawDescGZIP(), []int{6}
}

func (x *ListFunctions) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

type Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Runtime       string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	GuildId       string                 `protobuf:"bytes,5,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_api_v1_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_api_v1_models_proto_rawDescGZIP(), []int{7}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Function) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Function) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Function) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

var File_api_v1_models_proto protoreflect.FileDescriptor

const file_api_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/models.proto\x12\x02v1\"=\n" +
	"\n" +
	"GetContext\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\tR\aguildId\"X\n" +
	"\x04Args\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\"^\n" +
	"\bCommands\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\x04args\x18\x03 \x03(\v2\b.v1.ArgsR\x04args\"2\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xe0\x01\n" +
	"\tBuildFunc\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12\x19\n" +
	"\bguild_id\x18\x03 \x01(\tR\aguildId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12(\n" +
	"\bcommands\x18\x06 \x03(\v2\f.v1.CommandsR\bcommands\x12$\n" +
	"\aenvvars\x18\a \x03(\v2\n" +
	".v1.EnvVarR\aenvvars\"\xc7\x01\n" +
	"\vContextResp\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\tR\aguildId\x12\x1d\n" +
	"\n" +
	"guild_name\x18\x03 \x01(\tR\tguildName\x12\x1d\n" +
	"\n" +
	"server_url\x18\x04 \x01(\tR\tserverUrl\x12'\n" +
	"\x0fcurrent_context\x18\x05 \x01(\bR\x0ecurrentContext\x12\x19\n" +
	"\bjw_token\x18\x06 \x01(\tR\ajwToken\";\n" +
	"\rListFunctions\x12*\n" +
	"\tfunctions\x18\x01 \x03(\v2\f.v1.FunctionR\tfunctions\"\x8f\x01\n" +
	"\bFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12\x19\n" +
	"\bguild_id\x18\x05 \x01(\tR\aguildIdB,Z*github.com/f4tal-err0r/discord_faas/api/v1b\x06proto3"

var (
	file_api_v1_models_proto_rawDescOnce sync.Once
	file_api_v1_models_proto_rawDescData []byte
)

func file_api_v1_models_proto_rawDescGZIP() []byte {
	file_api_v1_models_proto_rawDescOnce.Do(func() {
		file_api_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_models_proto_rawDesc), len(file_api_v1_models_proto_rawDesc)))
	})
	return file_api_v1_models_proto_rawDescData
}

var file_api_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_models_proto_goTypes = []any{
	(*GetContext)(nil),    // 0: v1.GetContext
	(*Args)(nil),          // 1: v1.Args
	(*Commands)(nil),      // 2: v1.Commands
	(*EnvVar)(nil),        // 3: v1.EnvVar
	(*BuildFunc)(nil),     // 4: v1.BuildFunc
	(*ContextResp)(nil),   // 5: v1.ContextResp
	(*ListFunctions)(nil), // 6: v1.ListFunctions
	(*Function)(nil),      // 7: v1.Function
}
var file_api_v1_models_proto_depIdxs = []int32{
	1, // 0: v1.Commands.args:type_name -> v1.Args
	2, // 1: v1.BuildFunc.commands:type_name -> v1.Commands
	3, // 2: v1.BuildFunc.envvars:type_name -> v1.EnvVar
	7, // 3: v1.ListFunctions.functions:type_name -> v1.Function
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_models_proto_init() }
func file_api_v1_models_proto_init() {
	if File_api_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_models_proto_rawDesc), len(file_api_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_models_proto_goTypes,
		DependencyIndexes: file_api_v1_models_proto_depIdxs,
		MessageInfos:      file_api_v1_models_proto_msgTypes,
	}.Build()
	File_api_v1_models_proto = out.File
	file_api_v1_models_proto_goTypes = nil
	file_api_v1_models_proto_depIdxs = nil
}
