apiVersion: v1
kind: ServiceAccount
metadata:
  name: discord-faas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discord-faas-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discord-faas-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discord-faas-role
subjects:
  - kind: ServiceAccount
    name: discord-faas
    namespace: faas  