apiVersion: v1
kind: Service
metadata:
  name: discord-faas
spec:
  selector:
    app: discord-faas
  ports:
  - port: 8080
    targetPort: 8085
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discord-faas
  labels:
    name: discord-faas
spec:
  ingressClassName: nginx
  rules:
  - host: apps.voidnet.dev
    http:
      paths:
      - pathType: Prefix
        path: "/dfaas"
        backend:
          service:
            name: discord-faas
            port: 
              number: 8080
