apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discord-faas
spec:
  selector:
    matchLabels:
      app: discord-faas
  serviceName: discord-faas
  replicas: 2
  template:
    metadata:
      labels:
        app: discord-faas
    spec:
      containers:
      - name: discord-faas-controller
        command: ["/app/discord-faas"]
        args: ["start"]
        image: discord-faas
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /app/config.yml
            name: config
      volumes:
      - name: config
        configMap:
          name: discord-faas-config
  volumeClaimTemplates:
  - metadata:
      name: discord-faas
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
