# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/service.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'proto/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\"%\n\x08\x46uncmeta\x12\n\n\x02Id\x18\x01 \x01(\t\x12\r\n\x05MsgId\x18\x02 \x01(\t\"\"\n\x04\x46ile\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04Name\x18\x02 \x01(\t\"\x94\x01\n\x0e\x44iscordContent\x12\x0f\n\x07\x43ommand\x18\x01 \x01(\t\x12\'\n\x04\x41rgs\x18\x02 \x03(\x0b\x32\x19.DiscordContent.ArgsEntry\x12\x1b\n\x08\x46uncmeta\x18\x03 \x01(\x0b\x32\t.Funcmeta\x1a+\n\tArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"`\n\x0b\x44iscordResp\x12\x0f\n\x07Message\x18\x01 \x01(\t\x12\r\n\x05\x45mbed\x18\x02 \x01(\t\x12\x14\n\x05\x46iles\x18\x03 \x03(\x0b\x32\x05.File\x12\x1b\n\x08\x46uncmeta\x18\x04 \x01(\x0b\x32\t.Funcmeta\"t\n\x08\x46uncInit\x12\x0f\n\x07GuildId\x18\x01 \x01(\t\x12\'\n\x07Secrets\x18\x02 \x03(\x0b\x32\x16.FuncInit.SecretsEntry\x1a.\n\x0cSecretsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32p\n\x0b\x44iscordFaaS\x12\x35\n\x14HandleDiscordCommand\x12\x0f.DiscordContent\x1a\x0c.DiscordResp\x12*\n\x12InitializeFunction\x12\t.FuncInit\x1a\t.FuncmetaB+Z)github.com/f4tal-err0r/discord_faas/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/f4tal-err0r/discord_faas/proto'
  _globals['_DISCORDCONTENT_ARGSENTRY']._loaded_options = None
  _globals['_DISCORDCONTENT_ARGSENTRY']._serialized_options = b'8\001'
  _globals['_FUNCINIT_SECRETSENTRY']._loaded_options = None
  _globals['_FUNCINIT_SECRETSENTRY']._serialized_options = b'8\001'
  _globals['_FUNCMETA']._serialized_start=23
  _globals['_FUNCMETA']._serialized_end=60
  _globals['_FILE']._serialized_start=62
  _globals['_FILE']._serialized_end=96
  _globals['_DISCORDCONTENT']._serialized_start=99
  _globals['_DISCORDCONTENT']._serialized_end=247
  _globals['_DISCORDCONTENT_ARGSENTRY']._serialized_start=204
  _globals['_DISCORDCONTENT_ARGSENTRY']._serialized_end=247
  _globals['_DISCORDRESP']._serialized_start=249
  _globals['_DISCORDRESP']._serialized_end=345
  _globals['_FUNCINIT']._serialized_start=347
  _globals['_FUNCINIT']._serialized_end=463
  _globals['_FUNCINIT_SECRETSENTRY']._serialized_start=417
  _globals['_FUNCINIT_SECRETSENTRY']._serialized_end=463
  _globals['_DISCORDFAAS']._serialized_start=465
  _globals['_DISCORDFAAS']._serialized_end=577
# @@protoc_insertion_point(module_scope)
