apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discord-faas.fullname" . }}-config
  labels:
    {{- include "discord-faas.labels" . | nindent 4 }}
data:
  # Add your configuration key-value pairs here
  config.yaml: |
    {{- if .Values.minioSidecar.enabled }}
    s3_hostname: s3://{{ include "discord-faas.fullname" . }}:9000
    {{- else }}
    s3_hostname: {{ required "A valid .Values.storage.s3.hostname entry required!" .Values.storage.s3.hostname | b64enc | quote }}
    {{- end }}
{{ .Values.faas.config | toYaml | indent 4 }}
