{{- $token := .Values.discord.botToken | required "A valid .Values.discord.botToken entry required!" }}
{{- $clientid := .Values.discord.clientid | required "A valid .Values.discord.clientid entry required!" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-faas.fullname" . }}
type: Opaque
data:
  DISCORD_TOKEN: {{ $token | b64enc | quote }}
  DISCORD_CLIENTID: {{ $clientid | b64enc | quote }}
  {{- if .Values.faas.config.JWTSecretKey }}
  JWT_SECRET_KEY: {{ .Values.faas.config.JWTSecretKey | b64enc | quote }}
  {{- end }}
---
{{- if .Values.minioSidecar.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-faas.fullname" . }}-s3-creds
type: Opaque
data:
  S3_USERNAME: {{ required "A valid .Values.minioSidecar.rootUser entry required!" .Values.minioSidecar.rootUser | b64enc | quote }}
  S3_PASSWORD: {{ required "A valid .Values.minioSidecar.rootPassword entry required!" .Values.minioSidecar.rootPassword | b64enc | quote }}
{{- end }}
